### ISSUE TITLE
<InputGroup> borders do not fully highlight when clicking in <Input> form field

### ISSUE THREAD

**Issue by aaronrosenberg** [creativetimofficial/ct-black-dashboard-pro-react#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version <-- Not sure, but I bought it on May 2 though!
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

`<InputGroup>` borders should fully highlight all the way around when clicking into an `<Input>` form field.

Interestingly, the behavior *is* correct on the Bootstrap site: 
https://themes.getbootstrap.com/preview/?theme_id=8214&show_new=

# Current Behavior

The UI behavior in the code archive received (I purchased the ALL Bundle package) does not fully highlight around the `<InputGroup>` area.   It only changes the color of the `<Input>` and does not highlight the border of `<InputGroupAddon>`.

In humanspeak, when you click on an input on either the Register or Input pages, the border color highlight does not properly extend all around the displayed box.  In other words, the prepend does not get highlighted.

The current creative-tim Live Preview also has this defect (unlike the Bootstrap URL above):  
https://demos.creative-tim.com/black-dashboard-pro-react/#/auth/register

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to Register or Login Page (using the code distributed with the All Themes bundle purchase or the Creative Tim Live Preview link above.)
2. Click on an Input Field
3. Observe the partial highlight

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:  Macbook Pro 13-inch 2017, 2.5 i7
* Operating System: Mac OSX 14.4
* Browser and Version: Firefox Developer Edition 68.0b1

## Failure Logs

No errors are displayed in console.log().

**Comment by aaronrosenberg** [comment]
![register_border_highlight_missing](https://user-images.githubusercontent.com/205420/57876206-ce5c9900-77e2-11e9-8fc6-47cb8b530f5a.png)

**Comment by einazare** [comment]
Hello there, @aaronrosenberg ,

Thank you for your interest in working with our products and thank you for signaling this issue to us.
This issue is actually covered in our live docs here: https://demos.creative-tim.com/black-dashboard-pro-react/#/documentation/forms (Search for `With Nucleo Icons`)
So, right now the code looks something like this:
```
import React from "react";

import {
  Input,
  InputGroup,
  InputGroupAddon,
  InputGroupText
} from "reactstrap";

class Forms extends React.Component {
  render(){
    return (
      <>
        <InputGroup>
          <InputGroupAddon addonType="prepend">
            <InputGroupText><i className="tim-icons icon-single-02"></i></InputGroupText>
          </InputGroupAddon>
          <Input
            type="text"
            placeholder="With Nucleo Icons"
          />
        </InputGroup>
      </>
    );
  }
};

export default Forms;
```

When in fact it should look something like this:
```
import React from "react";
import classnames from "classnames";

import {
  Input,
  InputGroup,
  InputGroupAddon,
  InputGroupText
} from "reactstrap";

class Forms extends React.Component {
  state = {};
  render(){
    return (
      <>
        <InputGroup className={classnames({
          "input-group-focus": this.state.focus
        })}>
          <InputGroupAddon addonType="prepend">
            <InputGroupText><i className="tim-icons icon-single-02"></i></InputGroupText>
          </InputGroupAddon>
          <Input
            type="text"
            placeholder="With Nucleo Icons"
            onFocus={e => this.setState({ focus: true })}
            onBlur={e => this.setState({ focus: false })}
          />
        </InputGroup>
      </>
    );
  }
};

export default Forms;
```

Note the fact that, when the user focuses the input, we create a state parameter, named here `focus` (be careful, if you have multiple inputs, you will need to have multiple state parameters, `focus1`, `focus2`, `focus3`,...`focusx`, and so on, I think you get the point), and we add the value `true` for that parameter (so `onFocus`, the `focus` state parameter is `true`). Now when this happens, due to the fact that parameter is true, on the `InputGroup` component we add the class `input-group-focus` which ensure that the whole `InputGroup` will have a focused border. When the contrary happens, i.e. the input loses its focus (for example the user clicks outside the input), we now want to make that state variable`false`, hence the usage of the `onBlur` function. When this happens, we delete the `input-group-focus` class from the `InputGroup` component.

Hope this information was of help, and sorry for this behavior - we've just forgotten to add this on our `Register` page - we will repair our mistake with the above solution in the future update.

Please leave the issue opened.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by aaronrosenberg** [comment]
Thanks.    I can confirm that the new code works just fine.   However, is a scss change is necessary as well?  The border color is blue which is not standard on the theme.  ...for the register and login example pages anyway...

![blue_border](https://user-images.githubusercontent.com/205420/57925486-63f53880-7876-11e9-809f-df0d4100526f.png)

**Comment by aaronrosenberg** [comment]
FWIW, it looks like something is defaulting to $info instead of $primary.   Not sure since the documentation appears to follow a different theme than the register and login pages.  Still looking!

**Comment by einazare** [comment]
Hello again, @aaronrosenberg ,

We've decided for the React version of the product to make the form controls default to $info (since React is associated with the blue color - the React logo is blue).
You can delete that from this file: `src/assets/scss/black-dashboard-pro-react/react/_inputs.scss`.
You can safely delete that file and the colors will go back to the $primary ones.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* Check my Medium tutorial articles: https://medium.com/@einazare
* Check my YouTube tutorials: https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w/playlists
* Check my Udemy tutorials: https://www.udemy.com/user/axelutalex/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by aaronrosenberg** [comment]
Okay, that's fine - to just keep things sane for the brief while I've added the following to the .login-page and .register-page blocks in _example_pages.scss:

```
.form-group:not(.has-danger):not(.has-success),
.input-group-focus:not(.has-danger):not(.has-success) {
    .input-group-prepend .input-group-text,
    .input-group-append .input-group-text {
        border-color: $primary;
    }
    .form-control {
        &:focus {
            border-color: $primary;
            & + .input-group-append .input-group-text,
            & ~ .input-group-append .input-group-text,
            & + .input-group-prepend .input-group-text,
            & ~ .input-group-prepend .input-group-text {
                border: 1px solid $primary;
            }
        }
    }
}
```

Once I get a little more comfortable with the architecture and how the theme mechanics work, I'll no doubt take a more intelligent approach, like you describe.  Thanks for the help!

**Comment by aaronrosenberg** [comment]
Also, since the graphic themes of several pages - again like register and login - seem to use the fuschia/#e14eca color, will you be redoing some of the header graphics in a new release to be more fully coordinated?  It would help me personally to see how the new more-integrated UI color system functions from a user experience perspective. 
![color_variables](https://user-images.githubusercontent.com/205420/57931528-a757a300-7886-11e9-84a4-8a6f9d26504a.png)

**Comment by einazare** [comment]
> Also, since the graphic themes of several pages - again like register and login - seem to use the fuschia/#e14eca color, will you be redoing some of the header graphics in a new release to be more fully coordinated? It would help me personally to see how the new more-integrated UI color system functions from a user experience perspective.
> ![color_variables](https://user-images.githubusercontent.com/205420/57931528-a757a300-7886-11e9-84a4-8a6f9d26504a.png)

Hello again, @aaronrosenberg ,

Since the product is React based we wanted to make more pages closer to a React template.
That is why some colors have been changed from $primary to $info.
All these differences can be found inside `src/assets/scss/black-dashboard-pro-react/react`.
But I do not quite fully understand your last comment - are there differences between the live version and the downloaded version, or are there differences between the Designer code and the Web code?

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

**Comment by aaronrosenberg** [comment]
The question was more around redoing the graphic images that also mirror the $primary theme color.   It's minor, but when the whole UI doesn't coordinate together - it makes new unfamiliar customers wonder what they themselves are doing wrong if anything.
![primary_ux_system](https://user-images.githubusercontent.com/205420/57937004-1804bc80-7893-11e9-885d-18b9b1188955.png)
.

**Comment by einazare** [comment]
Hello again, @aaronrosenberg ,

I'll speak with our designers about this, and on our next update, we'll try to redo those images.

Best,
Manu

**Comment by Johnny-Fung** [comment]
Is there a way to automatically add a number format while using Input and InputGroup? For example, when inputting currency: 1923800 will turn into 1,923,800?

**Comment by einazare** [comment]
Hello there, @Johnny-Fung ,

Thank you for your interest in working with our products.
At the moment, there is no way to achieve that.
Maybe this will help you: https://stackoverflow.com/questions/38076985/format-number-in-an-html5-input-tag

Best,
Manu
