### ISSUE TITLE
[Bug] Sweet Alert 1 Warnings

### ISSUE THREAD

**Issue by Maxdola** [creativetimofficial/ct-black-dashboard-pro-react#18]
### Version
1.0.0
### Reproduction link
https://github.com/sweetalert2/sweetalert2
### Operating System
Windows
### Device
/
### Browser & Version
/
### Steps to reproduce
1. Launch a sweetalert and you get the following errors: http://prntscr.com/pe2cme
### What is expected?
To open without errors
### What is actually happening?
Opening with errors

---
### Solution
Upgrade Sweetalert1 to sweetalert2

**Comment by einazare** [comment]
Hello there, @Maxdola ,

Thank you for your interest in working with our products.
We wanted to use something that was React-based.
We will discuss this on our next board meeting to see if it is better to use sweetalert2 instead. I believe at some point in time, it was using jQuery, this being another argument for which we used the react-bootstrap-sweetalert plugin.

Thank you for letting us know.

Best,
Manu

**Comment by Maxdola** [comment]
@EINazare but with react 17.x it will stop working since the lifecycle methods are beeing remodeled.

**Comment by einazare** [comment]
Hello again, @Maxdola ,

We do not recommend changing our dependencies, we do not offer support for this.
We encourage our users to wait for or our updates.

If that happens, we will change the react-bootstrap-sweetalert plugin with something else, I believe with the sweetalert2, since now it isn't using jQuery anymore.

Best,
Manu
