### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by UYasin** [creativetimofficial/ct-black-dashboard-pro-react#9]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I downloaded all the files and ran the build and it worked fine. But now it gives me an error saying it will not compile because the modules have not been found

# Current Behavior

the dashboard wont load because of directory issues

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1: download the files and run them (they should work fine) 
2. step 2: store them in a private github repository then pull the files and run them

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Macbook pro
* Operating System: macOS Mojave 10.14.3
* Browser and Version: Chrome version 73.0.3683.103

## Failure Logs

![image](https://user-images.githubusercontent.com/36346577/56817276-49014c80-6813-11e9-8054-c71015066f52.png)

**Comment by einazare** [comment]
Hello there @UYasin ,

Thank you for your interest in working with our products.
Sorry for this late response, since I am a Christian I've had some free days for the Easter Holiday: 
- https://www.calendar-12.com/holidays/easter
- https://www.officeholidays.com/religious/orthodox/orthodox_easter.php

Please detail this:
>step 2: store them in a private github repository then pull the files and run them

Our product is already on a private repository and it works just fine, the image is where it should be:
<img width="1525" alt="Screen Shot 2019-04-30 at 10 07 48 AM" src="https://user-images.githubusercontent.com/26245512/56945482-0485f180-6b30-11e9-875e-9a77ad17e43b.png">

Will wait for your response.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.
